Mảng 1 chiều

In [16]:
import numpy as np

In [17]:
a = np.array([1,2,3])

In [5]:
a

array([1, 2, 3])

In [6]:
print(a)
a[0]

[1 2 3]


1

In [7]:
a.shape

(3,)

Mảng 2 chiều

In [18]:
b= np.array([[1,2,3],[4,5,6]])

In [10]:
b.shape

(2, 3)

In [13]:
b[1,1]
# or b[1][1]

5

Mảng ngẩu nhiên

In [20]:
c= np.random.random((2,3))
c

array([[0.59790221, 0.3813732 , 0.60100227],
       [0.78558127, 0.00309408, 0.40977547]])

Reshape

In [25]:
d = np.array([1,2,3,4,5,6,7,8,9])
d.reshape(3,-1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
b.reshape(6)

array([1, 2, 3, 4, 5, 6])

so sánh numpy

In [29]:
b>3

array([[False, False, False],
       [ True,  True,  True]])

In [31]:
d[d>3]

array([4, 5, 6, 7, 8, 9])

Tính toán numpy

In [32]:
a*b

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [35]:
e=np.array([[3,2,1],[6,5,4]])
b/e

array([[0.33333333, 1.        , 3.        ],
       [0.66666667, 1.        , 1.5       ]])

In [37]:
d.sum()

45

In [38]:
d.max()

9

In [39]:
d.min()

1

Nhân ma trận

In [41]:
A = np.array([[1,2],
              [2,1],
              [3,2],
              [4,5]])
A

array([[1, 2],
       [2, 1],
       [3, 2],
       [4, 5]])

In [43]:
B= np.array([[3,2,1],[4,5,6]])
B

array([[3, 2, 1],
       [4, 5, 6]])

ValueError: ignored